In [1]:
import pandas as pd

In [40]:
df = pd.read_json('performanceRecords.json')
df = df.drop(['detail','entryType','duration'], axis=1).merge(df.detail.apply(pd.Series), left_index=True, right_index=True)
df['step'] = df['name'].apply(lambda x: '_'.join(x.split('_')[1:]))
df['stepType'] = df['name'].apply(lambda x: x.split('_')[0])
df.drop('name',axis=1,inplace=True)
df.set_index(['implementation', 'step','stepType'],inplace=True)
df.sort_index(inplace=True)
df

                                          startTime
implementation      step      stepType
BbsBlsSignature2020 SIGN_VC   END        906.948416
                              START      847.618583
                    VERIFY_VC END        959.714291
                              START      906.980041
zkpld               SIGN_VC   END       1068.714708
                              START      782.989000
                    VERIFY_VC END       1157.830958
                              START     1068.951500

In [51]:
df2 = df.unstack('stepType')['startTime']
df2

stepType                               END        START
implementation      step
BbsBlsSignature2020 SIGN_VC     906.948416   847.618583
                    VERIFY_VC   959.714291   906.980041
zkpld               SIGN_VC    1068.714708   782.989000
                    VERIFY_VC  1157.830958  1068.951500

In [52]:
df2.END - df2.START

implementation       step
BbsBlsSignature2020  SIGN_VC       59.329833
                     VERIFY_VC     52.734250
zkpld                SIGN_VC      285.725708
                     VERIFY_VC     88.879458
dtype: float64