In [2]:
import pandas as pd

In [65]:
df = pd.read_json('performanceRecords.json')
df = df.drop(['detail','entryType','duration'], axis=1).merge(df.detail.apply(pd.Series), left_index=True, right_index=True)
df['step'] = df['name'].apply(lambda x: '_'.join(x.split('_')[1:]))
df['stepType'] = df['name'].apply(lambda x: x.split('_')[0])
df.drop('name',axis=1,inplace=True)
df.set_index(['implementation', 'step','stepType'],inplace=True)
df.sort_index(inplace=True)
df

                                                 startTime
implementation              step      stepType
BbsBlsSignature2020         SIGN_VC   END       581.182208
                                      START     529.843916
                            VERIFY_VC END       632.378875
                                      START     581.204541
Ed25519Signature2020        SIGN_VC   END       497.372083
                                      START     451.795791
                            VERIFY_VC END       518.799833
                                      START     497.385791
bbs-termwise-signature-2023 SIGN_VC   END       727.449291
                                      START     371.989791
                            VERIFY_VC END       815.673166
                                      START     727.827833

In [66]:
df2 = df.unstack('stepType')['startTime']
df2

stepType                                      END       START
implementation              step
BbsBlsSignature2020         SIGN_VC    581.182208  529.843916
                            VERIFY_VC  632.378875  581.204541
Ed25519Signature2020        SIGN_VC    497.372083  451.795791
                            VERIFY_VC  518.799833  497.385791
bbs-termwise-signature-2023 SIGN_VC    727.449291  371.989791
                            VERIFY_VC  815.673166  727.827833

In [67]:
df2_diff = df2.END - df2.START
df2_diff = df2_diff.unstack('implementation')
df2_diff.round(2)

implementation,BbsBlsSignature2020,Ed25519Signature2020,bbs-termwise-signature-2023
step,,,
SIGN_VC,51.34,45.58,355.46
VERIFY_VC,51.17,21.41,87.85